---
abstract: 'Type constraints for numbers'
author:
  - 'Brendan Byrd <BBYRD@CPAN.org>'
build_requires:
  IO::Handle: 1.27_02
  List::Util: 1.20
  Test::CheckDeps: 0.007
  Test::Exception: 0.27
  Test::More: 0.94
  Test::TypeTiny: 0.001
  Type::Tiny: 0
  base: 2.14
  perl: 5.008009
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Types-Numbers
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Types::Numbers:
    file: lib/Types/Numbers.pm
    version: 0.91_01
requires:
  Data::Float: 0.008
  Data::Integer: 0.004
  Math::BigFloat: 1.59
  Math::BigInt: 1.88
  Type::Library: 0.008
  Type::Tiny: 0.001
  Types::Standard: 0.001
  constant: 1.16
  perl: v5.8.8
  warnings: 1.05_01
resources:
  X_irc: irc://irc.perl.org/#web-simple
  bugtracker: https://github.com/SineSwiper/Types-Numbers/issues
  homepage: https://github.com/SineSwiper/Types-Numbers/wiki
  repository: git://github.com/SineSwiper/Types-Numbers.git
version: 0.91_01
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: '@Author::BBYRD/ReportPhase'
      version: 0.03
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::BBYRD/MakeMaker'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::BBYRD/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::BBYRD/Git::GatherDir'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::BBYRD/OurPkgVersion'
      version: 0.005000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugin: '@Author::BBYRD'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
      name: '@Author::BBYRD/PodWeaver'
      version: 3.102000
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::BBYRD/PruneCruft'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: '@Author::BBYRD/GitFmtChanges'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::BBYRD/ManifestSkip'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::BBYRD/Manifest'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::BBYRD/License'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmePodInRoot'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmeTextInBuild'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmeHTMLInBuild'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::BBYRD/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::BBYRD/ExecDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::BBYRD/Test::Compile'
      version: 2.033
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::BBYRD/PodCoverageTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::BBYRD/PodSyntaxTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Author::BBYRD/RunExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::BBYRD/NoTabsTests'
      version: 0.04
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Author::BBYRD/Test::EOL'
      version: 0.08
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::BBYRD/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: '@Author::BBYRD/Test::CheckDeps'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::BBYRD/Test::Portability'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@Author::BBYRD/Test::Synopsis'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::BBYRD/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::BBYRD/Test::ReportPrereqs'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Author::BBYRD/Test::CheckManifest'
      version: 0.04
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::BBYRD/Test::DistManifest'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::BBYRD/Test::Version'
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::BBYRD/@Prereqs/AutoPrereqs'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::BBYRD/@Prereqs/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MinimumPrereqs
      name: '@Author::BBYRD/@Prereqs/MinimumPrereqs'
      version: 0.92
    -
      class: Dist::Zilla::Plugin::PrereqsClean
      name: '@Author::BBYRD/@Prereqs/PrereqsClean'
      version: 0.92
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::BBYRD/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::BBYRD/MetaConfig'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::BBYRD/MetaJSON'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::BBYRD/MetaYAML'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::BBYRD/MetaNoIndex'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::BBYRD/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package: {}
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::BBYRD/MetaProvides::Package'
      version: 1.15000000
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: '@Author::BBYRD/MetaResourcesFromGit'
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@Author::BBYRD/ContributorsFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::BBYRD/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::TravisYML
      name: '@Author::BBYRD/TravisYML'
      version: 1.04
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::BBYRD/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::BBYRD/Git::CommitBuild'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::BBYRD/@Git/Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::BBYRD/@Git/Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::BBYRD/@Git/Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::BBYRD/@Git/Push'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Author::BBYRD/GitHub::Update'
      version: 0.35
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::BBYRD/TestRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::BBYRD/ConfirmRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::BBYRD/UploadToCPAN'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::BBYRD/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Author::BBYRD/Clean'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::RemovePrereqs
      config:
        Dist::Zilla::Plugin::RemovePrereqs:
          modules_to_remove:
            - Type::Exception
      name: RemovePrereqs
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300039
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300039
x_contributors:
  - 'Brendan Byrd <bbyrd@cpan.org>'
